<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class roomSeeder extends Seeder
{
    public function run(): void
    {
        // id_number_pic merujuk ke kolom id_number di tabel pics
   

        DB::table('rooms')->insert([
            // ===== building A =====
            [
                'room_code'      => 'A-101',
                'room_name'      => 'Ruang Kelas A101',
                'capacity'         => 40,
                'facility'         => 'Proyektor, AC, Whiteboard',
                'room_description' => 'Ruang kelas standar floor 1',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/a101.jpg',
                'building_id'         => 1,
                'id_number_pic'   => 20230001,
                'floor_number'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'A-102',
                'room_name'      => 'Ruang Kelas A102',
                'capacity'         => 40,
                'facility'         => 'Proyektor, AC, Whiteboard',
                'room_description' => 'Ruang kelas standar floor 1',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/a102.jpg',
                'building_id'         => 1,
                'id_number_pic'   => 20230001,
                'floor_number'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'A-103',
                'room_name'      => 'Ruang Kelas A103',
                'capacity'         => 35,
                'facility'         => 'Proyektor, AC, Whiteboard',
                'room_description' => 'Ruang kelas standar floor 1',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/a103.jpg',
                'building_id'         => 1,
                'id_number_pic'   => 20230001,
                'floor_number'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'A-104',
                'room_name'      => 'Ruang Rapat A104',
                'capacity'         => 20,
                'facility'         => 'Proyektor, AC, Whiteboard, TV',
                'room_description' => 'Ruang rapat kecil floor 1',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/a104.jpg',
                'building_id'         => 1,
                'id_number_pic'   => 20230001,
                'floor_number'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'A-201',
                'room_name'      => 'Ruang Lab Komputer A201',
                'capacity'         => 30,
                'facility'         => 'Komputer, AC, Proyektor',
                'room_description' => 'Laboratorium komputer floor 2',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/a201.jpg',
                'building_id'         => 1,
                'id_number_pic'   => 20230001,
                'floor_number'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'A-202',
                'room_name'      => 'Ruang Lab Jaringan A202',
                'capacity'         => 25,
                'facility'         => 'Komputer, Switch, Router, AC, Proyektor',
                'room_description' => 'Laboratorium jaringan komputer floor 2',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/a202.jpg',
                'building_id'         => 1,
                'id_number_pic'   => 20230001,
                'floor_number'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'A-203',
                'room_name'      => 'Ruang Kelas A203',
                'capacity'         => 40,
                'facility'         => 'Proyektor, AC, Whiteboard',
                'room_description' => 'Ruang kelas standar floor 2',
                'room_status'    => 'maintenance',
                'path_foto'         => 'room/a203.jpg',
                'building_id'         => 1,
                'id_number_pic'   => 20230001,
                'floor_number'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'A-301',
                'room_name'      => 'Ruang Seminar A301',
                'capacity'         => 80,
                'facility'         => 'Proyektor, AC, Sound System, Podium',
                'room_description' => 'Ruang seminar capacity sedang floor 3',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/a301.jpg',
                'building_id'         => 1,
                'id_number_pic'   => 20230001,
                'floor_number'      => 3,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'A-302',
                'room_name'      => 'Ruang lecturer A302',
                'capacity'         => 15,
                'facility'         => 'AC, TV, Loker',
                'room_description' => 'Ruang kerja lecturer floor 3',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/a302.jpg',
                'building_id'         => 1,
                'id_number_pic'   => 20230001,
                'floor_number'      => 3,
                'created_at'        => now(),
                'updated_at' => now(),
            ],

            // ===== building B =====
            [
                'room_code'      => 'B-101',
                'room_name'      => 'Ruang Kelas B101',
                'capacity'         => 45,
                'facility'         => 'Proyektor, AC, Whiteboard',
                'room_description' => 'Ruang kelas besar floor 1',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/b101.jpg',
                'building_id'         => 2,
                'id_number_pic'   => 20230001,
                'floor_number'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'B-102',
                'room_name'      => 'Ruang Kelas B102',
                'capacity'         => 45,
                'facility'         => 'Proyektor, AC, Whiteboard',
                'room_description' => 'Ruang kelas besar floor 1',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/b102.jpg',
                'building_id'         => 2,
                'id_number_pic'   => 20230001,
                'floor_number'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'B-103',
                'room_name'      => 'Ruang Perpustakaan B103',
                'capacity'         => 60,
                'facility'         => 'AC, Rak Buku, Komputer',
                'room_description' => 'Perpustakaan fakultas floor 1',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/b103.jpg',
                'building_id'         => 2,
                'id_number_pic'   => 20230001,
                'floor_number'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'B-201',
                'room_name'      => 'Ruang Lab Fisika B201',
                'capacity'         => 30,
                'facility'         => 'Pertoolan Lab, AC, Proyektor',
                'room_description' => 'Laboratorium fisika dasar floor 2',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/b201.jpg',
                'building_id'         => 2,
                'id_number_pic'   => 20230001,
                'floor_number'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'B-202',
                'room_name'      => 'Ruang Lab Kimia B202',
                'capacity'         => 25,
                'facility'         => 'Pertoolan Lab Kimia, Lemari Asam, AC',
                'room_description' => 'Laboratorium kimia dasar floor 2',
                'room_status'    => 'tidak_tersedia',
                'path_foto'         => 'room/b202.jpg',
                'building_id'         => 2,
                'id_number_pic'   => 20230001,
                'floor_number'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'B-203',
                'room_name'      => 'Ruang Kelas B203',
                'capacity'         => 40,
                'facility'         => 'Proyektor, AC, Whiteboard',
                'room_description' => 'Ruang kelas standar floor 2',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/b203.jpg',
                'building_id'         => 2,
                'id_number_pic'   => 20230001,
                'floor_number'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'B-301',
                'room_name'      => 'Aula building B',
                'capacity'         => 200,
                'facility'         => 'Sound System, Proyektor, AC',
                'room_description' => 'Aula serbaguna floor 3',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/b301.jpg',
                'building_id'         => 2,
                'id_number_pic'   => 20230001,
                'floor_number'      => 3,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'B-302',
                'room_name'      => 'Ruang Rapat Besar B302',
                'capacity'         => 50,
                'facility'         => 'Proyektor, AC, Sound System, Whiteboard',
                'room_description' => 'Ruang rapat besar floor 3',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/b302.jpg',
                'building_id'         => 2,
                'id_number_pic'   => 20230001,
                'floor_number'      => 3,
                'created_at'        => now(),
                'updated_at' => now(),
            ],

            // ===== building C =====
            [
                'room_code'      => 'C-101',
                'room_name'      => 'Ruang Kelas C101',
                'capacity'         => 40,
                'facility'         => 'Proyektor, AC, Whiteboard',
                'room_description' => 'Ruang kelas standar floor 1',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/c101.jpg',
                'building_id'         => 3,
                'id_number_pic'   => 20230001,
                'floor_number'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'C-102',
                'room_name'      => 'Ruang Kelas C102',
                'capacity'         => 40,
                'facility'         => 'Proyektor, AC, Whiteboard',
                'room_description' => 'Ruang kelas standar floor 1',
                'room_status'    => 'maintenance',
                'path_foto'         => 'room/c102.jpg',
                'building_id'         => 3,
                'id_number_pic'   => 20230001,
                'floor_number'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'C-201',
                'room_name'      => 'Ruang Lab Multimedia C201',
                'capacity'         => 30,
                'facility'         => 'Komputer, Kamera, AC, Proyektor',
                'room_description' => 'Laboratorium multimedia floor 2',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/c201.jpg',
                'building_id'         => 3,
                'id_number_pic'   => 20230001,
                'floor_number'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'C-202',
                'room_name'      => 'Ruang Studio Rekaman C202',
                'capacity'         => 15,
                'facility'         => 'Pertoolan Rekaman, AC, Soundproof',
                'room_description' => 'Studio rekaman audio visual floor 2',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/c202.jpg',
                'building_id'         => 3,
                'id_number_pic'   => 20230001,
                'floor_number'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'room_code'      => 'C-301',
                'room_name'      => 'Ruang Sidang C301',
                'capacity'         => 30,
                'facility'         => 'Proyektor, AC, Meja Sidang, Sound System',
                'room_description' => 'Ruang sidang skripsi dan ujian floor 3',
                'room_status'    => 'tersedia',
                'path_foto'         => 'room/c301.jpg',
                'building_id'         => 3,
                'id_number_pic'   => 20230001,
                'floor_number'      => 3,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
