<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RuanganSeeder extends Seeder
{
    public function run(): void
    {
        // id_number_pic merujuk ke kolom id_number di tabel pics
   

        DB::table('ruangans')->insert([
            // ===== GEDUNG A =====
            [
                'kode_ruangan'      => 'A-101',
                'name_ruangan'      => 'Ruang Kelas A101',
                'kapasitas'         => 40,
                'fasilitas'         => 'Proyektor, AC, Whiteboard',
                'deskripsi_ruangan' => 'Ruang kelas standar lantai 1',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/a101.jpg',
                'id_gedung'         => 1,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'A-102',
                'name_ruangan'      => 'Ruang Kelas A102',
                'kapasitas'         => 40,
                'fasilitas'         => 'Proyektor, AC, Whiteboard',
                'deskripsi_ruangan' => 'Ruang kelas standar lantai 1',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/a102.jpg',
                'id_gedung'         => 1,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'A-103',
                'name_ruangan'      => 'Ruang Kelas A103',
                'kapasitas'         => 35,
                'fasilitas'         => 'Proyektor, AC, Whiteboard',
                'deskripsi_ruangan' => 'Ruang kelas standar lantai 1',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/a103.jpg',
                'id_gedung'         => 1,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'A-104',
                'name_ruangan'      => 'Ruang Rapat A104',
                'kapasitas'         => 20,
                'fasilitas'         => 'Proyektor, AC, Whiteboard, TV',
                'deskripsi_ruangan' => 'Ruang rapat kecil lantai 1',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/a104.jpg',
                'id_gedung'         => 1,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'A-201',
                'name_ruangan'      => 'Ruang Lab Komputer A201',
                'kapasitas'         => 30,
                'fasilitas'         => 'Komputer, AC, Proyektor',
                'deskripsi_ruangan' => 'Laboratorium komputer lantai 2',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/a201.jpg',
                'id_gedung'         => 1,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'A-202',
                'name_ruangan'      => 'Ruang Lab Jaringan A202',
                'kapasitas'         => 25,
                'fasilitas'         => 'Komputer, Switch, Router, AC, Proyektor',
                'deskripsi_ruangan' => 'Laboratorium jaringan komputer lantai 2',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/a202.jpg',
                'id_gedung'         => 1,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'A-203',
                'name_ruangan'      => 'Ruang Kelas A203',
                'kapasitas'         => 40,
                'fasilitas'         => 'Proyektor, AC, Whiteboard',
                'deskripsi_ruangan' => 'Ruang kelas standar lantai 2',
                'status_ruangan'    => 'maintenance',
                'path_foto'         => 'ruangan/a203.jpg',
                'id_gedung'         => 1,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'A-301',
                'name_ruangan'      => 'Ruang Seminar A301',
                'kapasitas'         => 80,
                'fasilitas'         => 'Proyektor, AC, Sound System, Podium',
                'deskripsi_ruangan' => 'Ruang seminar kapasitas sedang lantai 3',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/a301.jpg',
                'id_gedung'         => 1,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 3,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'A-302',
                'name_ruangan'      => 'Ruang lecturer A302',
                'kapasitas'         => 15,
                'fasilitas'         => 'AC, TV, Loker',
                'deskripsi_ruangan' => 'Ruang kerja lecturer lantai 3',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/a302.jpg',
                'id_gedung'         => 1,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 3,
                'created_at'        => now(),
                'updated_at' => now(),
            ],

            // ===== GEDUNG B =====
            [
                'kode_ruangan'      => 'B-101',
                'name_ruangan'      => 'Ruang Kelas B101',
                'kapasitas'         => 45,
                'fasilitas'         => 'Proyektor, AC, Whiteboard',
                'deskripsi_ruangan' => 'Ruang kelas besar lantai 1',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/b101.jpg',
                'id_gedung'         => 2,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'B-102',
                'name_ruangan'      => 'Ruang Kelas B102',
                'kapasitas'         => 45,
                'fasilitas'         => 'Proyektor, AC, Whiteboard',
                'deskripsi_ruangan' => 'Ruang kelas besar lantai 1',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/b102.jpg',
                'id_gedung'         => 2,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'B-103',
                'name_ruangan'      => 'Ruang Perpustakaan B103',
                'kapasitas'         => 60,
                'fasilitas'         => 'AC, Rak Buku, Komputer',
                'deskripsi_ruangan' => 'Perpustakaan fakultas lantai 1',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/b103.jpg',
                'id_gedung'         => 2,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'B-201',
                'name_ruangan'      => 'Ruang Lab Fisika B201',
                'kapasitas'         => 30,
                'fasilitas'         => 'Peralatan Lab, AC, Proyektor',
                'deskripsi_ruangan' => 'Laboratorium fisika dasar lantai 2',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/b201.jpg',
                'id_gedung'         => 2,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'B-202',
                'name_ruangan'      => 'Ruang Lab Kimia B202',
                'kapasitas'         => 25,
                'fasilitas'         => 'Peralatan Lab Kimia, Lemari Asam, AC',
                'deskripsi_ruangan' => 'Laboratorium kimia dasar lantai 2',
                'status_ruangan'    => 'tidak_tersedia',
                'path_foto'         => 'ruangan/b202.jpg',
                'id_gedung'         => 2,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'B-203',
                'name_ruangan'      => 'Ruang Kelas B203',
                'kapasitas'         => 40,
                'fasilitas'         => 'Proyektor, AC, Whiteboard',
                'deskripsi_ruangan' => 'Ruang kelas standar lantai 2',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/b203.jpg',
                'id_gedung'         => 2,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'B-301',
                'name_ruangan'      => 'Aula Gedung B',
                'kapasitas'         => 200,
                'fasilitas'         => 'Sound System, Proyektor, AC',
                'deskripsi_ruangan' => 'Aula serbaguna lantai 3',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/b301.jpg',
                'id_gedung'         => 2,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 3,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'B-302',
                'name_ruangan'      => 'Ruang Rapat Besar B302',
                'kapasitas'         => 50,
                'fasilitas'         => 'Proyektor, AC, Sound System, Whiteboard',
                'deskripsi_ruangan' => 'Ruang rapat besar lantai 3',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/b302.jpg',
                'id_gedung'         => 2,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 3,
                'created_at'        => now(),
                'updated_at' => now(),
            ],

            // ===== GEDUNG C =====
            [
                'kode_ruangan'      => 'C-101',
                'name_ruangan'      => 'Ruang Kelas C101',
                'kapasitas'         => 40,
                'fasilitas'         => 'Proyektor, AC, Whiteboard',
                'deskripsi_ruangan' => 'Ruang kelas standar lantai 1',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/c101.jpg',
                'id_gedung'         => 3,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'C-102',
                'name_ruangan'      => 'Ruang Kelas C102',
                'kapasitas'         => 40,
                'fasilitas'         => 'Proyektor, AC, Whiteboard',
                'deskripsi_ruangan' => 'Ruang kelas standar lantai 1',
                'status_ruangan'    => 'maintenance',
                'path_foto'         => 'ruangan/c102.jpg',
                'id_gedung'         => 3,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 1,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'C-201',
                'name_ruangan'      => 'Ruang Lab Multimedia C201',
                'kapasitas'         => 30,
                'fasilitas'         => 'Komputer, Kamera, AC, Proyektor',
                'deskripsi_ruangan' => 'Laboratorium multimedia lantai 2',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/c201.jpg',
                'id_gedung'         => 3,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'C-202',
                'name_ruangan'      => 'Ruang Studio Rekaman C202',
                'kapasitas'         => 15,
                'fasilitas'         => 'Peralatan Rekaman, AC, Soundproof',
                'deskripsi_ruangan' => 'Studio rekaman audio visual lantai 2',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/c202.jpg',
                'id_gedung'         => 3,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 2,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
            [
                'kode_ruangan'      => 'C-301',
                'name_ruangan'      => 'Ruang Sidang C301',
                'kapasitas'         => 30,
                'fasilitas'         => 'Proyektor, AC, Meja Sidang, Sound System',
                'deskripsi_ruangan' => 'Ruang sidang skripsi dan ujian lantai 3',
                'status_ruangan'    => 'tersedia',
                'path_foto'         => 'ruangan/c301.jpg',
                'id_gedung'         => 3,
                'id_number_pic'   => 20230001,
                'nomor_lantai'      => 3,
                'created_at'        => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
